version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=l1ttle4ngels
      - POSTGRES_DB=childcare
    volumes:
      - childcare_pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: l1ttle4ngels
    depends_on:
      - postgres

volumes:
  childcare_pg_data:
